### ISSUE TITLE
OpenShift deployment

### ISSUE THREAD

**Issue by HolySamosa** [wso2/kubernetes-apim#121]
Is it safe to assume that the new Kubernetes resources could be deployed to OpenShift by substituting the equivalent `oc` CLI command for each `kubectl` CLI command?  

Or would *Helm* be the preferred approach for OpenShift?

Thanks!

**Comment by fsbano** [comment]
Is there any progress?

Best Regards,
Fábio Sbano

**Comment by Chathuru** [comment]
We have developed OpenShift resources for WSO2 products. For wso2-apim version 3.1.0 you can find the OpenShift resource in https://github.com/Chathuru/wso2-openshift-apim here. We will merge these resources into WSO2 repose soon.

**Comment by chirangaalwis** [comment]
@HolySamosa @fsbano Adding to what @Chathuru has mentioned and as per the issue discussed here, we now recommend users to utilize the Openshift specific resources which we are in the process of developing, for WSO2 product deployments in Openshift platform.

Plus, it has to be noted that we recommend users to use WSO2 product Helm charts for production grade deployments in Kubernetes based environments.

Since, the development of Openshift resources can be tracked from @fsbano's issue (https://github.com/wso2/kubernetes-apim/issues/334) and the Openshift resource specific repositories which would be made available soon, I will be closing this issue.

Please feel free to reopen this issue if needed.
