### ISSUE TITLE
How to deploy gateway without datasource ?

### ISSUE THREAD

**Issue by Vincent1984** [wso2/kubernetes-apim#156]
**Description:**
How to deploy gateway without config datasources.
as the component flow chat 
![image](https://user-images.githubusercontent.com/3183359/46774861-2c9a3880-cd37-11e8-94c1-117003b36ada.png)

gateway does not need to connect DB, but when we deploy this component we config the datasources as necessary, It does not make sense.  and it cost too many connections when gateway is deploying. **how can we deploy the gateway component without DB config ?**  

**Suggested Labels:**
deployment in Kubernetes 

**Suggested Assignees:**
pubudu538@gmail.com

**Affected Product Version:**
wso2am 2.5.0

**Comment by chirangaalwis** [comment]
@Vincent1984 +1. As you have mentioned earlier, it is not required to explicitly define database connections from the Gateway component node to outside. Actually, the Gateway does not require any DB interactions in theory. Hence, you can keep the default configurations that are defined in `<WSO2_PRODUCT_HOME>/repository/conf/datasources/master-datasources.xml` as they are just to be on the safe side even if they are not actually used. Please see the official documentation defining the database configurations from [1] for further details.

Please note that this needs to be fixed in Kubernetes resources for WSO2 API Manager pattern 2.

[1]: [Configuring databases in a distributed deployment of WSO2 API Manager](https://docs.wso2.com/display/AM250/Installing+and+Configuring+the+Databases)

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-apim/pull/173 in Kubernetes resources for WSO2 API Manager v2.6.x. Thus, closing the issue.
