### ISSUE TITLE
Config error in 2.1.0/pattern-2/dockerfiles/apim-pubstore-tm-2/carbon/repository/conf/api-manager.xml : PolicyDeployer>/<ServiceURL

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#24]
Hi,

Is the hostname at https://github.com/wso2/kubernetes-apim/blob/2.1.0/pattern-2/dockerfiles/apim-pubstore-tm-2/carbon/repository/conf/api-manager.xml#L592 is wso2apim-pubstore-tm-2.default.svc instead of wso2apim-pubstore-tm-1.default.svc

This is what is done in https://github.com/wso2/kubernetes-apim/blob/2.1.0/pattern-2/dockerfiles/apim-pubstore-tm-1/carbon/repository/conf/api-manager.xml#L592

Thanks
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

Both configurations are pointing to wso2apim-pubstore-tm-1.default.svc which is the node 1. When you deploy a throttling policy, that is getting deployed in node 1. We have used rsync to sync the same artifact in both nodes. Due to this we have to point to node 1 in the configuration in both nodes. Rsync is happening from node 1 to node 2. Therefore, we cannot deploy the throttling policy in node 2.

Thank you!
Pubudu

**Comment by yhilem** [comment]
Hi Pubudu,

We don't use rsync. We use a shared folder (NFS).
So we do not modify this config?

Thanks
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

In that case, you can point to localhost.

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Thank you Pubudu.
