### ISSUE TITLE
Use MySQL DB for message broker database

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#28]
Hi,

H2 is used for for message broker database (https://github.com/wso2/kubernetes-apim/blob/2.1.0/pattern-2/dockerfiles/apim-pubstore-tm-1/carbon/repository/conf/datasources/master-datasources.xml#L118).

H2 DB is not recommend for a production environment (http://wso2-oxygen-tank.10903.n7.nabble.com/Traffic-Manager-HA-deployment-on-DC-OS-td146737.html)

Also, we have more than one Traffic Manager node, and each Traffic Manager node must have its own WSO2_MB_STORE_DB database (https://docs.wso2.com/display/AM210/Distributed+Deployment+of+API+Manager).

Thanks
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

WSO2_MB_STORE_DB is used for traffic manager and it stores mb related information. What stores within this database is not critical and only useful for the traffic manager server. Due to this, you can use H2 database for MB_Store. 

If you prefer to go with production ready database, then there is no restriction limiting that. Also, every traffic manager node requires its own MB_Store database. 

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Hi Pubudu,

If I understand correctly, we can use H2 in production environment for WSO2_MB_STORE_DB.

Thanks
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

Yes, as there is no critical impact on the traffic manager nodes.

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Thank you Pubudu.
