### ISSUE TITLE
After using [helm install] to install am-pattern-1 or 2 of WSO2, the browser displays [503 Service Temporarily Unavailable]

### ISSUE THREAD

**Issue by 13940344135** [wso2/kubernetes-apim#374]
**Description:**
After using [helm install] to install am-pattern-1 or 2 of WSO2, the browser displays [503 Service Temporarily Unavailable]

**Steps to reproduce:**
After executing the [helm install] command, execute [kubectl get ing -n default], output:
NAME: ap1
LAST DEPLOYED: Wed Apr 29 15:41:49 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1

Execute the command [kubectl get ing -n default], output:
NAME HOSTS ADDRESS PORTS AGE
wso2am-pattern-1-am-analytics-dashboard-ingress ap1-analytics-dashboard 192.168.1.106 80, 443 24m
wso2am-pattern-1-am-gateway-ingress ap1-gateway 192.168.1.106 80, 443 24m
wso2am-pattern-1-am-ingress ap1-am 192.168.1.106 80, 443 24m

The above output looks correct，
but，
At this time visit https: // <RELEASE_NAME> -am / carbon, the browser will display [503 Service Temporarily Unavailable]

Execute the [kubectl get pods] command and find that the status of the pod is pending.
NAME                                                              READY   STATUS    RESTARTS   AGE
ap1-nfs-server-provisioner-0                                      1/1     Running   1          53m
wso2am-mysql-db-service-5944c9bbd9-2vj7j                          1/1     Running   0          53m
wso2am-pattern-1-am-1-deployment-0                                0/1     Running   0          53m
wso2am-pattern-1-am-2-deployment-0                                0/1     Pending   0          53m
wso2am-pattern-1-am-analytics-dashboard-deployment-556d86b2w86r   1/1     Running   0          53m
wso2am-pattern-1-am-analytics-worker-2-deployment-5556b5b596ng7   0/1     Running   0          53m
wso2am-pattern-1-am-analytics-worker-deployment-56659c49f4qx9wv   1/1     Running   0          53m

It is strange that the pods in the pending state are different after each reinstallation.

Execute the [kubectl describe pod <podname>] command, there are the following warnings.

Events:
  Type     Reason            Age                  From               Message
  Warning  FailedScheduling  119s (x16 over 15m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims

**Affected Product Version:**
The version of my installation tool is as follows:
minikube 1.9.2
kubernetes-cli 1.16.2
kubernetes-helm 3.2.0
kubernetes 1.16.9
wso2/am-pattern-1 --version 3.1.0-2

**Comment by chirangaalwis** [comment]
@13940344135 we don't recommend you to install production grade WSO2 product Helm Charts in an evaluatory platform such as, Minikube. This is since,

- Such a production grade deployment will require significant amount of resources for the deployment
- The discussed deployment involves the use of [NFS Server Provisioner](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) user for persistence/sharing of artifacts in a high availability deployment of APIM. The NFS Server Provisioner does not possess a source (i.e. an NFS server) to dynamically create the required Persistent Volumes in such a deployment. Thus, the PersistentVolumeClaims are unbound to any storage.

Thus, if it is for evaluatory purposes we recommend you to use the [simplified WSO2 product deployment](https://wso2.com/api-management/install/kubernetes/get-started/). A platform like Minikube would suffice for such a deployment.

If you intend to create a production grade deployment of a WSO2 product pattern in a Kubernetes environment, we recommend you to use a production grade Kubernetes cluster (i.e. a multi node Kubernetes cluster for example using a cloud service provider or bare-metal).

For advanced details on choosing installation artifacts for container based deployments of WSO2 products, you may refer to [this](https://medium.com/faun/wso2-products-containerized-the-missing-guide-for-choosing-installation-artifacts-7503c9ce971a) article.

**Comment by chirangaalwis** [comment]
@13940344135 please let us know if https://github.com/wso2/kubernetes-apim/issues/374#issuecomment-622459321 was helpful to you.

If this resolved your issue, please close this issue. Else, please feel free to raise any questions or issues you are facing.

**Comment by 13940344135** [comment]
@chirangaalwis 
Sorry, the recovery was not timely.

How much resources does am-pattern-1 require?
I used i7 cpu + 32GB memory + 100G hard drive

now，I will use bare metal to create a multi-node Kubernetes cluster，How many resources should I prepare at least?
