### ISSUE TITLE
[v3.1.x] Add Ingress Definition Entry For Path `/data-provider`

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-apim#381]
**Description:**
It has been reported that when clicking on any of the Dashboards (Admin, Publisher, Developer Portal) to view the data, it keeps on loading and no data become visible. The referred resources are the Helm resources for WSO2 API Management deployment pattern 3.

When checking the network trace it was identified that the issue is with the Web Socket connection to `wss://apimanager-analytics-dashboard/data-provider` which fails with `404 Not Found`.

**Affected Product Version:**
Helm Resources For WSO2 API Management version `3.1.0.2`

**Comment by Prasadi-R** [comment]
The above issue was observed in an AWS EKS based Kubernetes deployment for WSO2 API Manager version 3.1.0 (v3.1.0.2) when having NGINX Ingress Controller **version 0.30.0** for AWS (L7) [1].
The WebSocket connection to load "/data-provider" endpoint to view the data in the Analytics Dashboards, failed with "HTTP 404 Not Found" status code as follows,
![wss_loading_issue](https://user-images.githubusercontent.com/38277473/87922056-0e7b7380-ca99-11ea-991a-06de762d3177.png)

The issue was narrowed down to a specific behavior/ issue in the NGINX version-0.30.0 (ELB) or previous NGINX versions.

**Possible solution:**
In order to get rid of the issue, upgrade the NGINX Ingress Controller **version to 0.32.0** (NLB) or the latest [2]. 

[1] https://github.com/kubernetes/ingress-nginx/blob/nginx-0.30.0/docs/deploy/index.md#elastic-load-balancer---elb
[2] https://kubernetes.github.io/ingress-nginx/deploy/#network-load-balancer-nlb

**Comment by chirangaalwis** [comment]
As per https://github.com/wso2/kubernetes-apim/issues/381#issuecomment-660918905, since no resource changes are required, closing this issue.
