### ISSUE TITLE
Simple Helm Chart installation Issue

### ISSUE THREAD

**Issue by AmilaJ** [wso2/kubernetes-apim#584]
**Description:**
Latest Helm chart for simple deployment get deployed when installed from the repo directly. The chart dependencies does not get resolved even when resolved via the source files.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
4.2.0-1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
helm repo add wso2 https://helm.wso2.com && helm repo update
helm install wso2amsingle wso2/am-single-node --version 4.2.0-1 --namespace wso2 --create-namespace

**Related Issues:**

**Comment by PasanT9** [comment]
Hi Amila,

Thanks for bringing the issue to our attention.
The Helm chart was not getting installed correctly due to an issue with packaging that resulted in required dependencies not being included in the package.

To resolve this issue, I have repackaged the chart with required dependencies and pushed to the Helm repository.
