### ISSUE TITLE
Move from Deployment resource to StatefulSet resource

### ISSUE THREAD

**Issue by pubudu538** [wso2/kubernetes-apim#72]
**Description:**
In Kubernetes, deployment is for the stateless applications and statefulset is for stateful applications. We should move to statefulset.

https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

**Comment by ldipotetjob** [comment]
Hi Pubudu, this comment  [ is in reference of wso2am pattern1 in kubernetes ?](https://github.com/wso2/kubernetes-apim/blob/master/pattern-1/apim/wso2apim-deployment.yam). It is not clear some best practices that are not in this yaml definition. wso2am should be an  StatefulSets instead of a Deployment or am I wrong?

**Comment by pubudu538** [comment]
HI @ldipotetjob,

Yes, it needs to be a StatefulSet and not a Deployment kind. 
@chirangaalwis We may need to fix this in the coming releases. 

Thank you!
Pubudu.

**Comment by chirangaalwis** [comment]
@pubudu538 +1.

We are currently in the process of evaluating the usage and benefits of Kubernetes StatefulSets. I will update this issue as we progress.

**Comment by chirangaalwis** [comment]
Fixed in referenced PRs.
