### ISSUE TITLE
Config error in PolicyDeployer:ServiceURL for pattern-3/dockerfiles/apim-pubstore-tm-2/carbon/repository/conf/api-manager.xml

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#8]
Hi,

Is the value of PolicyDeployer:ServiceURL for pattern-3/dockerfiles/apim-pubstore-tm-2/carbon/repository/conf/api-manager.xml should be <ServiceURL>https://localhost:${mgt.transport.https.port}${carbon.context}services/</ServiceURL> and not <ServiceURL>https://pubstore-tm-km-1:9443${carbon.context}services/</ServiceURL> ?

Example : the value of PolicyDeployer:ServiceURL for pattern-3/dockerfiles/apim-pubstore-tm-1/carbon/repository/conf/api-manager.xml is <ServiceURL>https://localhost:${mgt.transport.https.port}${carbon.context}services/</ServiceURL>

In addition, the hostname pubstore-tm-km-1 is not defined for pattern-3.

Thanks,
Youcef HILEM

**Comment by pubudu538** [comment]
Thank you Youcef for bringing this up. Actually, we may have to update the files. We need to use hostname rather than localhost to avoid any SSL issues. Both nodes should need to point to node-1 as we do the deployment synchronization from node-1. Both nodes will deploy the policies in node-1. The second node will fetch the policy from node-1. Yes, the hostname pubstore-tm-km-1 should be changed to wso2apim-manager-worker.default.svc

**Comment by yhilem** [comment]
Thank you.
